### PR TITLE
[WIP] Add some methods and redefine method naming

### PR DESCRIPTION
**Pull request by cristianoc72**
See discussion on issue #2

- [X] Change method naming: all transformations now have the form `to*` (i.e. `capitalize()` now is `toCapitalCase()`)
- [X] Add `toSingular` and `toPlural` methods, based on [propel/pluralizer](https://github.com/cristianoc72/pluralizer)
- [X] Add some useful *isser* methods (basically wrapped around `ctype` functions)
- [x] Verify that all checks have the form `is*`
- [x] Add some case transformations: `toSnakeCase`, `toCamelCase`, `toStudlyCase`, `toKebapCase`
- [x] Improve code coverage

### CODE REVIEW

**Comment by gossi** [comment]
Really good stuff I see here, very nice. One thing - you couldn't know - is, because I want to mimic "bare language" features, the very basics (similar to `java.lang`), I would have this package without any dependencies. Any ideas? Or maybe need I adjust to not having this?

**Comment by cristianoc72** [comment]
Well, I can see 2 possible solutions:
1. I could move here the pluralizer library, I exctracted from Propel (https://github.com/cristianoc72/pluralizer). It's very easy to do since it's made of one class and one interface. The only issue I can see is that we will have to fight fiercely for the coding standard :smile: (pluralizer class follows PSR-2).
2. Remove singularize/pluralize methods

I vote for 1, of course.

P.S. I splitted the method I added into 2 traits, to improve mantainability, as suggested by Scrutinizer analysis.

**Comment by gossi** [comment]
@cristianoc72 is this ready to merge?

**Comment by cristianoc72** [comment]
Yes it is. Do you prefere I put EnglishPluralizer in a separate namespace? (Now it is in`phootwork\lang`, I could put it in `phootwork\lang\pluralizer`)

**Comment by gossi** [comment]
I will look at the code myself now and see if I will add something to it on top of your stuff. I will also move pluralizer to  `phootwork\lang\text` 😉 - that looks best to me. Watch out for a new release, so you can benefit from propel side 👍 

Thanks a thousand times for your work ❤️

**Comment by cristianoc72** [comment]
Thank you for this library!

**Pull request merged**
